DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(100) NULL DEFAULT NULL COMMENT '密码',
    email VARCHAR(100) NULL DEFAULT NULL COMMENT '邮箱',
    type VARCHAR(100) NULL DEFAULT NULL COMMENT '类型',
    PRIMARY KEY (id)
);

CREATE TABLE site
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(100) NULL DEFAULT NULL COMMENT '地点名称',
    place VARCHAR(100) NULL DEFAULT NULL COMMENT '地址',
    type VARCHAR(100) NULL DEFAULT NULL COMMENT '类型',
    status VARCHAR(100) NULL DEFAULT NULL COMMENT '是否开放',
    book VARCHAR(100) NULL DEFAULT NULL COMMENT '是否允许现场预约',
    time VARCHAR(100) NULL DEFAULT NULL COMMENT '平均等待时间',    
    PRIMARY KEY (id)
);