DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    password VARCHAR(100) NULL DEFAULT NULL COMMENT '密码',
    email VARCHAR(100) NULL DEFAULT NULL COMMENT '邮箱',
    type VARCHAR(100) NULL DEFAULT NULL COMMENT '类型',
    PRIMARY KEY (id)
);

CREATE TABLE site
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(100) NULL DEFAULT NULL COMMENT '地点名称',
    place VARCHAR(100) NULL DEFAULT NULL COMMENT '地址',
    type VARCHAR(100) NULL DEFAULT NULL COMMENT '类型',
    status VARCHAR(100) NULL DEFAULT NULL COMMENT '是否开放',
    book VARCHAR(100) NULL DEFAULT NULL COMMENT '是否允许现场预约',
    time VARCHAR(100) NULL DEFAULT NULL COMMENT '平均等待时间',    
    PRIMARY KEY (id)
);

CREATE TABLE booking
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    uid BIGINT(20) NULL DEFAULT NULL COMMENT 'uid',
    pin VARCHAR(100) NULL DEFAULT NULL COMMENT 'pin码',
    status VARCHAR(100) NULL DEFAULT NULL COMMENT '检测状态',
    type VARCHAR(100) NULL DEFAULT NULL COMMENT '测试类型（PCR、RAT）',
    qrcode VARCHAR(100) NULL DEFAULT NULL COMMENT '二维码',
    url VARCHAR(100) NULL DEFAULT NULL COMMENT '链接',
    PRIMARY KEY (id)
);